stages:
  - package
  - publish
 
package:jessie: &package
  stage: package
  image: $CI_REGISTRY/docker-images/layers:$DISTRO-deb
  variables:
    DISTRO: jessie
  script:
    - package
  artifacts:
    paths:
      - pkg/

package:stretch:
  <<: *package
  variables:
    DISTRO: stretch

publish:
  stage: publish
  tags: 
    - shell
  script:
    - publish

