stages:
  - test
  - package
  - publish
 
test:jessie: &test
  stage: test
  image: $CI_REGISTRY/docker-images/layers:$DISTRO-deb
  variables:
    DISTRO: jessie
  script:
    - apt-get install check libev-dev net-tools dpkg-dev libsubunit-dev
    - make clean
    - make build 
    - make test

package:jessie: &package
  stage: package
  image: $CI_REGISTRY/docker-images/layers:$DISTRO-deb
  variables:
    DISTRO: jessie
  script:
    - package
  artifacts:
    paths:
      - pkg/

test:stretch:
  <<: *test
  variables:
    DISTRO: stretch

package:stretch:
  <<: *package
  variables:
    DISTRO: stretch

publish:
  stage: publish
  tags: 
    - shell
  script:
    - publish

